config/routes.rb
Rails.application.routes.draw do
  root to: 'leads#index'

  devise_for :admins

  resources :leads
  get '/next' => 'leads#next'
  get '/no_leads' => 'leads#no_leads'
  get '/token' => 'leads#token'
  post '/voice' => 'leads#voice'
  post '/text' => 'leads#text'
  
  get '/settings/edit' => 'user_settings#edit'
  patch '/settings' => 'user_settings#update'

  get '/leads/edit/:id' => 'leads#edit'
  post '/leads/edit/:id' => 'leads#auto_text'

  get '/daily_logs' => 'daily_progress_logs#index'

  post '/incoming_voice' => 'webhooks#incoming_voice'
  post '/incoming_text' => 'webhooks#incoming_text'

  namespace :api do
    namespace :v1 do
      get '/leads' => 'leads#index'
      get '/leads' => 'leads#show'
      # get '/leads/edit/1' => 'leads#edit'
      post '/leads/:id' => 'leads#create'

    end
  end

end

app/models/user_setting.rb
class UserSetting < ApplicationRecord
  belongs_to :admin
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  def edit
    @user_setting = UserSetting.find_by(admin_id: current_admin.id)
    puts "I'm working!"
    puts @user_setting
  end

  def update
    @user_setting = UserSetting.find_by(admin_id: current_admin.id)
    puts params[:user_setting][:text_message]
    if @user_setting.update(text_message: params[:user_setting][:text_message])
      flash[:success] = "Settings saved!"
      redirect_to '/'
    else
      flash[:error] = "ERROR: We could not update your settings."
      redirect_to '/settings/edit'
    end
  end

end

app/helpers/user_settings_helper.rb
module UserSettingsHelper
end

app/views/user_settings/_user_setting_form.erb
<%= form_for @user_setting, url: settings_path(@user_setting), html: { method: :patch } do |f| %>
<div class="form-group">
  <%= f.label :text_message, "Auto-Text" %>
    <%= f.text_field :text_message, class: 'form-control' %>
</div>
<div class="row">
  <div class="col-md-6" id="update-btn-col">
    <%= f.submit :update, {value: "Save", class: 'btn btn-primary btn-lg update-btn'} %>
  </div>
</div>
<% end %>

app/views/user_settings/edit.html.erb
<section class="forms">
  <div class="container-fluid">

  <%= render 'user_setting_form' %>

  </div>
</section>